// Farsi Localization for Servaan Admin Panel
// محلی‌سازی فارسی برای پنل مدیریت سِروان

export const fa = {
  // Common
  common: {
    loading: 'در حال بارگذاری...',
    error: 'خطا',
    success: 'موفقیت',
    warning: 'هشدار',
    info: 'اطلاعات',
    save: 'ذخیره',
    cancel: 'انصراف',
    delete: 'حذف',
    edit: 'ویرایش',
    view: 'مشاهده',
    add: 'افزودن',
    search: 'جستجو',
    filter: 'فیلتر',
    refresh: 'تازه‌سازی',
    export: 'خروجی',
    import: 'ورودی',
    download: 'دانلود',
    upload: 'آپلود',
    close: 'بستن',
    back: 'بازگشت',
    next: 'بعدی',
    previous: 'قبلی',
    submit: 'ثبت',
    reset: 'بازنشانی',
    confirm: 'تأیید',
    yes: 'بله',
    no: 'خیر',
    ok: 'باشه',
    actions: 'عملیات',
    status: 'وضعیت',
    date: 'تاریخ',
    time: 'زمان',
    name: 'نام',
    email: 'ایمیل',
    phone: 'تلفن',
    address: 'آدرس',
    description: 'توضیحات',
    notes: 'یادداشت‌ها',
    created: 'ایجاد شده',
    updated: 'به‌روزرسانی شده',
    lastLogin: 'آخرین ورود',
    role: 'نقش',
    permissions: 'دسترسی‌ها',
    settings: 'تنظیمات',
    profile: 'پروفایل',
    logout: 'خروج',
    login: 'ورود',
    register: 'ثبت‌نام',
    password: 'رمز عبور',
    currentPassword: 'رمز عبور فعلی',
    newPassword: 'رمز عبور جدید',
    confirmPassword: 'تأیید رمز عبور',
    rememberMe: 'مرا به خاطر بسپار',
    forgotPassword: 'فراموشی رمز عبور',
    twoFactorCode: 'کد احراز هویت دو مرحله‌ای',
  },

  // Navigation
  navigation: {
    dashboard: 'داشبورد',
    tenants: 'مستأجرین',
    users: 'کاربران',
    analytics: 'تحلیل‌ها',
    security: 'امنیت',
    system: 'سیستم',
    support: 'پشتیبانی',
    reports: 'گزارش‌ها',
    settings: 'تنظیمات',
    profile: 'پروفایل',
    logout: 'خروج',
  },

  // Dashboard
  dashboard: {
    title: 'داشبورد مدیریت',
    welcome: 'خوش آمدید',
    welcomeBack: 'خوش برگشتی',
    overview: 'نمای کلی',
    summary: 'خلاصه',
    quickActions: 'عملیات سریع',
    recentActivity: 'فعالیت‌های اخیر',
    systemHealth: 'سلامت سیستم',
    performance: 'عملکرد',
    alerts: 'هشدارها',
    notifications: 'اعلان‌ها',
    lastUpdated: 'آخرین به‌روزرسانی',
    viewAll: 'مشاهده همه',
    generateReport: 'ایجاد گزارش',
    systemSettings: 'تنظیمات سیستم',
  },

  // Statistics
  stats: {
    totalTenants: 'کل مستأجرین',
    activeTenants: 'مستأجرین فعال',
    totalUsers: 'کل کاربران',
    activeUsers: 'کاربران فعال',
    monthlyRevenue: 'درآمد ماهانه',
    systemHealth: 'سلامت سیستم',
    uptime: 'زمان کارکرد',
    responseTime: 'زمان پاسخ',
    cpuUsage: 'استفاده از پردازنده',
    memoryUsage: 'استفاده از حافظه',
    diskUsage: 'استفاده از دیسک',
    networkIO: 'ورودی/خروجی شبکه',
    transactions: 'تراکنش‌ها',
    orders: 'سفارشات',
    customers: 'مشتریان',
    items: 'کالاها',
    suppliers: 'تأمین‌کنندگان',
  },

  // Status
  status: {
    active: 'فعال',
    inactive: 'غیرفعال',
    pending: 'در انتظار',
    suspended: 'معلق',
    cancelled: 'لغو شده',
    completed: 'تکمیل شده',
    failed: 'ناموفق',
    processing: 'در حال پردازش',
    online: 'آنلاین',
    offline: 'آفلاین',
    healthy: 'سالم',
    warning: 'هشدار',
    critical: 'بحرانی',
    maintenance: 'تعمیر و نگهداری',
    error: 'خطا',
    success: 'موفق',
    info: 'اطلاعات',
  },

  // Tenants
  tenants: {
    title: 'مدیریت مستأجرین',
    addTenant: 'افزودن مستأجر جدید',
    editTenant: 'ویرایش مستأجر',
    deleteTenant: 'حذف مستأجر',
    tenantDetails: 'جزئیات مستأجر',
    tenantName: 'نام مستأجر',
    subdomain: 'زیردامنه',
    businessType: 'نوع کسب‌وکار',
    city: 'شهر',
    country: 'کشور',
    plan: 'طرح',
    status: 'وضعیت',
    ownerName: 'نام مالک',
    ownerEmail: 'ایمیل مالک',
    ownerPhone: 'تلفن مالک',
    maxUsers: 'حداکثر کاربران',
    maxItems: 'حداکثر کالاها',
    maxCustomers: 'حداکثر مشتریان',
    createdAt: 'تاریخ ایجاد',
    lastActive: 'آخرین فعالیت',
    storageUsed: 'فضای استفاده شده',
    storageLimit: 'محدودیت فضا',
    userCount: 'تعداد کاربران',
    features: 'ویژگی‌ها',
    billing: 'صورتحساب',
    support: 'پشتیبانی',
  },

  // Users
  users: {
    title: 'مدیریت کاربران',
    addUser: 'افزودن کاربر جدید',
    editUser: 'ویرایش کاربر',
    deleteUser: 'حذف کاربر',
    userDetails: 'جزئیات کاربر',
    firstName: 'نام',
    lastName: 'نام خانوادگی',
    fullName: 'نام کامل',
    username: 'نام کاربری',
    email: 'ایمیل',
    phone: 'تلفن',
    role: 'نقش',
    permissions: 'دسترسی‌ها',
    isActive: 'فعال',
    lastLogin: 'آخرین ورود',
    loginCount: 'تعداد ورود',
    createdAt: 'تاریخ ایجاد',
    updatedAt: 'تاریخ به‌روزرسانی',
    tenant: 'مستأجر',
    workspace: 'فضای کاری',
    department: 'بخش',
    position: 'سمت',
    manager: 'مدیر',
    subordinates: 'زیردستان',
  },

  // Analytics
  analytics: {
    title: 'تحلیل‌ها و گزارش‌ها',
    overview: 'نمای کلی',
    trends: 'روندها',
    comparisons: 'مقایسه‌ها',
    performance: 'عملکرد',
    revenue: 'درآمد',
    growth: 'رشد',
    conversion: 'تبدیل',
    retention: 'حفظ',
    engagement: 'تعامل',
    demographics: 'جمعیت‌شناسی',
    behavior: 'رفتار',
    funnel: 'قیف فروش',
    cohort: 'گروه‌بندی',
    heatmap: 'نقشه حرارتی',
    realTime: 'زمان واقعی',
    historical: 'تاریخی',
    custom: 'سفارشی',
    export: 'خروجی',
    schedule: 'زمان‌بندی',
  },

  // Security
  security: {
    title: 'امنیت و نظارت',
    authentication: 'احراز هویت',
    authorization: 'مجوزدهی',
    accessControl: 'کنترل دسترسی',
    auditLogs: 'گزارش‌های حسابرسی',
    loginAttempts: 'تلاش‌های ورود',
    failedLogins: 'ورودهای ناموفق',
    suspiciousActivity: 'فعالیت‌های مشکوک',
    ipAddresses: 'آدرس‌های IP',
    userAgents: 'عامل‌های کاربر',
    locations: 'مکان‌ها',
    devices: 'دستگاه‌ها',
    sessions: 'جلسات',
    tokens: 'توکن‌ها',
    apiKeys: 'کلیدهای API',
    rateLimiting: 'محدودیت نرخ',
    firewall: 'دیوار آتش',
    encryption: 'رمزگذاری',
    backups: 'پشتیبان‌گیری',
    compliance: 'انطباق',
  },

  // System
  system: {
    title: 'مدیریت سیستم',
    health: 'سلامت',
    monitoring: 'نظارت',
    performance: 'عملکرد',
    resources: 'منابع',
    logs: 'گزارش‌ها',
    errors: 'خطاها',
    warnings: 'هشدارها',
    maintenance: 'تعمیر و نگهداری',
    updates: 'به‌روزرسانی‌ها',
    backups: 'پشتیبان‌گیری',
    restore: 'بازیابی',
    configuration: 'پیکربندی',
    environment: 'محیط',
    database: 'پایگاه داده',
    cache: 'کش',
    queue: 'صف',
    cron: 'وظایف زمان‌بندی شده',
    api: 'رابط برنامه‌نویسی',
    webhooks: 'وب‌هوک‌ها',
    integrations: 'ادغام‌ها',
  },

  // Support
  support: {
    title: 'پشتیبانی و کمک',
    tickets: 'تیکت‌ها',
    createTicket: 'ایجاد تیکت',
    ticketDetails: 'جزئیات تیکت',
    priority: 'اولویت',
    status: 'وضعیت',
    category: 'دسته‌بندی',
    subject: 'موضوع',
    message: 'پیام',
    attachments: 'پیوست‌ها',
    responses: 'پاسخ‌ها',
    assignedTo: 'تخصیص داده شده به',
    createdAt: 'تاریخ ایجاد',
    updatedAt: 'تاریخ به‌روزرسانی',
    closedAt: 'تاریخ بسته شدن',
    resolution: 'راه‌حل',
    satisfaction: 'رضایت',
    feedback: 'بازخورد',
    knowledge: 'دانش',
    faq: 'سؤالات متداول',
    guides: 'راهنماها',
    tutorials: 'آموزش‌ها',
  },

  // Messages
  messages: {
    // Success messages
    loginSuccess: 'ورود موفقیت‌آمیز بود',
    logoutSuccess: 'خروج موفقیت‌آمیز بود',
    saveSuccess: 'اطلاعات با موفقیت ذخیره شد',
    deleteSuccess: 'آیتم با موفقیت حذف شد',
    updateSuccess: 'اطلاعات با موفقیت به‌روزرسانی شد',
    createSuccess: 'آیتم جدید با موفقیت ایجاد شد',
    
    // Error messages
    loginFailed: 'ورود ناموفق بود',
    invalidCredentials: 'اطلاعات ورود نامعتبر است',
    accessDenied: 'دسترسی رد شد',
    notFound: 'آیتم مورد نظر یافت نشد',
    serverError: 'خطای سرور رخ داد',
    networkError: 'خطای شبکه رخ داد',
    validationError: 'خطای اعتبارسنجی',
    requiredField: 'این فیلد الزامی است',
    invalidFormat: 'فرمت نامعتبر است',
    
    // Warning messages
    unsavedChanges: 'تغییرات ذخیره نشده است',
    confirmDelete: 'آیا از حذف این آیتم اطمینان دارید؟',
    sessionExpired: 'جلسه شما منقضی شده است',
    lowStorage: 'فضای ذخیره‌سازی کم است',
    highUsage: 'استفاده بالا از منابع',
    
    // Info messages
    loadingData: 'در حال بارگذاری اطلاعات...',
    noData: 'داده‌ای موجود نیست',
    searchResults: 'نتایج جستجو',
    filteredResults: 'نتایج فیلتر شده',
    showingResults: 'نمایش نتایج',
    totalResults: 'کل نتایج',
  },

  // Time and Date
  time: {
    now: 'اکنون',
    today: 'امروز',
    yesterday: 'دیروز',
    tomorrow: 'فردا',
    thisWeek: 'این هفته',
    lastWeek: 'هفته گذشته',
    nextWeek: 'هفته آینده',
    thisMonth: 'این ماه',
    lastMonth: 'ماه گذشته',
    nextMonth: 'ماه آینده',
    thisYear: 'امسال',
    lastYear: 'سال گذشته',
    nextYear: 'سال آینده',
    ago: 'قبل',
    in: 'در',
    from: 'از',
    to: 'تا',
    between: 'بین',
    duration: 'مدت',
    remaining: 'باقی‌مانده',
    overdue: 'معوق',
    scheduled: 'زمان‌بندی شده',
  },

  // Numbers and Currency
  numbers: {
    zero: 'صفر',
    one: 'یک',
    two: 'دو',
    three: 'سه',
    four: 'چهار',
    five: 'پنج',
    six: 'شش',
    seven: 'هفت',
    eight: 'هشت',
    nine: 'نه',
    ten: 'ده',
    hundred: 'صد',
    thousand: 'هزار',
    million: 'میلیون',
    billion: 'میلیارد',
    trillion: 'تریلیون',
    percent: 'درصد',
    decimal: 'اعشار',
    fraction: 'کسر',
    currency: 'واحد پول',
    rial: 'ریال',
    toman: 'تومان',
    dollar: 'دلار',
    euro: 'یورو',
  },

  // Actions
  actions: {
    view: 'مشاهده',
    edit: 'ویرایش',
    delete: 'حذف',
    create: 'ایجاد',
    update: 'به‌روزرسانی',
    save: 'ذخیره',
    cancel: 'انصراف',
    confirm: 'تأیید',
    approve: 'تأیید',
    reject: 'رد',
    activate: 'فعال‌سازی',
    deactivate: 'غیرفعال‌سازی',
    suspend: 'معلق کردن',
    restore: 'بازیابی',
    backup: 'پشتیبان‌گیری',
    export: 'خروجی',
    import: 'ورودی',
    download: 'دانلود',
    upload: 'آپلود',
    send: 'ارسال',
    receive: 'دریافت',
    start: 'شروع',
    stop: 'توقف',
    pause: 'توقف موقت',
    resume: 'ادامه',
    refresh: 'تازه‌سازی',
    reload: 'بارگذاری مجدد',
    search: 'جستجو',
    filter: 'فیلتر',
    sort: 'مرتب‌سازی',
    group: 'گروه‌بندی',
    expand: 'گسترش',
    collapse: 'فشرده‌سازی',
    show: 'نمایش',
    hide: 'مخفی',
    enable: 'فعال‌سازی',
    disable: 'غیرفعال‌سازی',
    configure: 'پیکربندی',
    customize: 'سفارشی‌سازی',
    manage: 'مدیریت',
    monitor: 'نظارت',
    analyze: 'تحلیل',
    report: 'گزارش',
    notify: 'اعلان',
    alert: 'هشدار',
    log: 'ثبت',
    audit: 'حسابرسی',
    secure: 'امن‌سازی',
    migrate: 'انتقال',
    upgrade: 'ارتقا',
    install: 'نصب',
    uninstall: 'حذف نصب',
    deploy: 'استقرار',
    rollback: 'بازگشت',
    scale: 'مقیاس‌بندی',
    optimize: 'بهینه‌سازی',
    maintain: 'نگهداری',
    repair: 'تعمیر',
    clean: 'پاک‌سازی',
    archive: 'آرشیو',
    sync: 'همگام‌سازی',
  },
};

export const en = {
  // English fallback for development/testing
  common: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    refresh: 'Refresh',
    export: 'Export',
    import: 'Import',
    download: 'Download',
    upload: 'Upload',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit',
    reset: 'Reset',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    actions: 'Actions',
    status: 'Status',
    date: 'Date',
    time: 'Time',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    description: 'Description',
    notes: 'Notes',
    created: 'Created',
    updated: 'Updated',
    lastLogin: 'Last Login',
    role: 'Role',
    permissions: 'Permissions',
    settings: 'Settings',
    profile: 'Profile',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    password: 'Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    rememberMe: 'Remember Me',
    forgotPassword: 'Forgot Password',
    twoFactorCode: 'Two-Factor Code',
  },
  // Add other English translations as needed...
};

export type Locale = 'fa' | 'en';
export type LocalizationKey = keyof typeof fa;

export const getLocalization = (locale: Locale = 'fa') => {
  return locale === 'fa' ? fa : en;
};

export const t = (key: string, locale: Locale = 'fa'): string => {
  const loc = getLocalization(locale);
  const keys = key.split('.');
  let value: any = loc;
  
  for (const k of keys) {
    if (value && typeof value === 'object' && k in value) {
      value = value[k];
    } else {
      return key; // Return key if translation not found
    }
  }
  
  return typeof value === 'string' ? value : key;
};

export default getLocalization;
